config/routes.rb
Rails.application.routes.draw do
  mount Spree::Core::Engine, at: '/'

  namespace :potepan do
    get :cart_page,                 to: 'sample#cart_page'
    get :checkout_step_1,           to: 'sample#checkout_step_1'
    get :checkout_step_2,           to: 'sample#checkout_step_2'
    get :checkout_step_3,           to: 'sample#checkout_step_3'
    get :checkout_complete,         to: 'sample#checkout_complete'
    get :blog_left_sidebar,         to: 'sample#blog_left_sidebar'
    get :blog_right_sidebar,        to: 'sample#blog_right_sidebar'
    get :blog_single_left_sidebar,  to: 'sample#blog_single_left_sidebar'
    get :blog_single_right_sidebar, to: 'sample#blog_single_right_sidebar'
    get :about_us,                  to: 'sample#about_us'
    get :tokushoho,                 to: 'sample#tokushoho'
    get :privacy_policy,            to: 'sample#privacy_policy'
    resources :products,            only: [:index, :show]
    resources :categories,          only: :show
    root to: 'static_pages#index'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/spree/option_type_decorator.rb
module Spree
  OptionType.class_eval do
    def self.names_classification_by_filter(filter_name)
      joins(:option_values).
        where(presentation: filter_name).
        select('spree_option_values.name, spree_option_values.id').
        order('name DESC')
    end
  end
end

app/models/spree/product_decorator.rb
module Spree
  Product.class_eval do
    scope :includes_master_price_images, -> {
      includes({ master: [:default_price, :images] })
    }
    scope :with_related_taxons, -> (product) {
      joins(:taxons).
        where(spree_taxons: { id: product.taxon_ids }).
        limit(Constants::RELATED_PRODUCTS_LIMIT)
    }
    scope :excluding, -> (product) { where.not(id: product.id).distinct }
    scope :limit_products, -> { limit(Constants::FEATURED_PRODUCTS_LIMIT) }
    scope :available_order, -> (order_option: :desc) {
      order(available_on: order_option)
    }
  end
end

app/models/spree/taxonomy_decorator.rb
module Spree
  Taxonomy.class_eval do
    scope :includes_taxons, -> { includes(taxons: :children) }
  end
end

app/models/spree/variant_decorator.rb
module Spree
  Variant.class_eval do
    scope :includes_option_values_price_images, -> {
      includes({ option_values: :option_type }, :default_price, :images)
    }
    scope :price_order, -> (order_option: :desc) {
      order("spree_prices.amount #{order_option}")
    }
    scope :available_order, -> (order_option: :desc) {
      order("spree_products.available_on #{order_option}")
    }
    scope :not_master, -> { where(is_master: false) }
    scope :includes_images, -> { includes(:images) }

    def self.counts_classification_by_filter(filter_name)
      # filter_nameによる分類の商品バリエーション各数量
      includes({ option_values: :option_type }, :default_price, :images).
        where(spree_option_types: { presentation: filter_name }).
        references(:option_values, :option_type, :default_price, :images).
        group('spree_option_values.name').count
    end

    def self.variants_classification_by_filter(filter_name, params_keyword)
      # filter_nameによる分類で、選択したparamsの商品バリエーション
      joins(option_values: :option_type).includes(:default_price, :images).
        where(spree_option_types: { presentation: filter_name }).
        where(spree_option_values: { name: params_keyword }).
        references(:default_price, :images)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/potepan/categories_controller.rb
class Potepan::CategoriesController < ApplicationController
  include Potepan::Concerns::ProductConcern

  def show
    @taxon = Spree::Taxon.find(params[:id])
    @taxonomies = Spree::Taxonomy.includes_taxons
    @products_of_taxon = Spree::Product.joins(:taxons).
      includes_master_price_images.where(spree_taxons: { id: @taxon.id }).
      references(:master, :default_price, :images).page(params[:page])

    # サイドバーの分類
    @hash_classification_by_filter = hash_classification_by_filter('Color')
  end
end

app/controllers/potepan/concerns/product_concern.rb
module Potepan::Concerns::ProductConcern
  extend ActiveSupport::Concern

  def hash_classification_by_filter(filter_option)
    {
      labels: Spree::OptionType.names_classification_by_filter(filter_option),
      counts: Spree::Variant.counts_classification_by_filter(filter_option),
    }
  end
end

app/controllers/potepan/products_controller.rb
class Potepan::ProductsController < ApplicationController
  include Potepan::Concerns::ProductConcern

  def index
    @taxonomies = Spree::Taxonomy.includes_taxons
    @color = params[:color]
    if @color.nil?
      @variants = Spree::Variant.includes_option_values_price_images.page(params[:page])
    else
      @variants = Spree::Variant.variants_classification_by_filter('Color', @color).
        page(params[:page])
    end
    @hash_classification_by_filter = hash_classification_by_filter('Color')
  end

  def show
    @product = Spree::Product.
      includes(:variants_including_master, { option_types: :option_values }, :properties).
      find(params[:id])
    @related_products = Spree::Product.
      includes_master_price_images.with_related_taxons(@product).excluding(@product)
  end
end

app/controllers/potepan/sample_controller.rb
class Potepan::SampleController < ApplicationController
  def index
  end

  def product_grid_left_sidebar
  end

  def product_list_left_sidebar
  end

  def single_product
  end

  def cart_page
  end

  def checkout_step_1
  end

  def checkout_step_2
  end

  def checkout_step_3
  end

  def checkout_complete
  end

  def blog_left_sidebar
  end

  def blog_right_sidebar
  end

  def blog_single_left_sidebar
  end

  def blog_single_right_sidebar
  end

  def about_us
  end

  def tokushoho
  end

  def privacy_policy
  end
end

app/controllers/potepan/static_pages_controller.rb
class Potepan::StaticPagesController < ApplicationController
  def index
    @featured_products = Spree::Product.available_order.limit_products
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title: "")
    base_title = "PotepanEC"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/products_helper.rb
module ProductsHelper
  def active_title(color: nil)
    if color.nil?
      "Products"
    else
      "Products of #{color}"
    end
  end
end

app/views/layouts/_footer.html.erb
<!-- FOOTER -->
  <div class="footer clearfix">
    <div class="container">
      <div class="row">
        <div class="col-sm-2 col-xs-12">
          <div class="footerLink">
            <h5>Accessories</h5>
            <ul class="list-unstyled">
              <li><a href="#">Body care </a></li>
              <li><a href="#">Chambray </a></li>
              <li><a href="#">Floral </a></li>
              <li><a href="#">Rejuvination </a></li>
              <li><a href="#">Shaving </a></li>
              <li><a href="#">Toilette </a></li>
            </ul>
          </div>
        </div>
        <div class="col-sm-2 col-xs-12">
          <div class="footerLink">
            <h5>BRANDS</h5>
            <ul class="list-unstyled">
              <li><a href="#">Barbour </a></li>
              <li><a href="#">Brioni </a></li>
              <li><a href="#">Oliver Spencer</a></li>
              <li><a href="#">Belstaff</a></li>
            </ul>
          </div>
        </div>
        <div class="col-sm-2 col-xs-12">
          <div class="footerLink">
            <h5>Accessories</h5>
            <ul class="list-unstyled">
              <li><a href="#">Body care </a></li>
              <li><a href="#">Chambray </a></li>
              <li><a href="#">Floral </a></li>
              <li><a href="#">Rejuvination </a></li>
              <li><a href="#">Shaving </a></li>
              <li><a href="#">Toilette </a></li>
            </ul>
          </div>
        </div>
        <div class="col-sm-2 col-xs-12">
          <div class="footerLink">
            <h5>Get in Touch</h5>
            <ul class="list-unstyled">
              <li>Call us at (555)-555-5555</li>
              <li><a href="mailto:support@iamabdus.com">support@iamabdus.com</a></li>
            </ul>
          </div>
        </div>
        <div class="col-sm-4 col-xs-12">
          <div class="newsletter clearfix">
            <h4>Newsletter</h4>
            <h3>Sign up now</h3>
            <p>Enter your email address and get notified about new products. We hate spam!</p>
            <div class="input-group">
              <input type="text" class="form-control" placeholder="your email address" aria-describedby="basic-addon2">
              <a href="#" class="input-group-addon" id="basic-addon2">go <i class="glyphicon glyphicon-chevron-right"></i></a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- COPY RIGHT -->
  <div class="copyRight clearfix">
    <div class="container">
      <div class="row">
        <div class="col-sm-7 col-xs-12">
          <p>&copy; 2016 Copyright Bigbag Store Bootstrap Template by <a target="_blank" href="http://www.iamabdus.com/">Abdus</a>.</p>
        </div>
        <div class="col-sm-5 col-xs-12">
          <ul class="list-inline">
            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
            <li><a href="#"><i class="fa fa-dribbble"></i></a></li>
            <li><a href="#"><i class="fa fa-vimeo"></i></a></li>
            <li><a href="#"><i class="fa fa-tumblr"></i></a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_meta.html.erb
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>

<!-- GOOGLE FONT -->
<%= stylesheet_link_tag "application", 'https://fonts.googleapis.com/css?family=Oxygen:400,300,700', :media => "all" %>

app/views/layouts/_rails_default_js.html.erb
<!-- JAVASCRIPT -->
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <%= render 'layouts/meta' %>
    <title><%= full_title(page_title: yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <div class="main-wrapper">
      <%= render 'layouts/header' %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  <%= render 'layouts/rails_default_js' %>
  </body>
</html>

app/views/potepan/categories/_products_grid.html.erb
<div class="row">
  <%= content_tag :div, paginate(@products_of_taxon), class: 'text-center' %>
  <% @products_of_taxon.each do |product| %>
      <div class="col-sm-4 col-xs-12">
        <div class="productBox">
          <div class="productImage clearfix">
            <%= image_tag(product.display_image.attachment(:small)) %>
            <div class="productMasking">
              <ul class="list-inline btn-group" role="group">
                <li><a data-toggle="modal" href=".login-modal" class="btn btn-default"><i class="fa fa-heart"></i></a></li>
                <li><a href="cart_page.html" class="btn btn-default"><i class="fa fa-shopping-cart"></i></a></li>
                <li><a class="btn btn-default" data-toggle="modal" href=".quick-view" ><i class="fa fa-eye"></i></a></li>
              </ul>
            </div>
          </div>
          <div class="productCaption clearfix">
            <h5><%= link_to product.name, potepan_product_path(product.id) %></h5>
            <h3><%= product.master.price %><%= product.cost_currency %></h3>
          </div>
        </div>
      </div>
  <% end %>
</div>
<%= content_tag :div, paginate(@products_of_taxon), class: 'text-center' %>

app/views/potepan/categories/_products_list.html.erb
<div class="row productListSingle">
  <%= content_tag :div, paginate(@products_of_taxon), class: 'text-center' %>
  <% @products_of_taxon.each do |product| %>
    <div class="col-xs-12">
      <div class="media">
        <div class="media-left">
          <%= image_tag(product.display_image.attachment(:product)) %>
          <span class="maskingImage"><a data-toggle="modal" href=".quick-view" class="btn viewBtn">Quick View</a></span>
        </div>
        <div class="media-body">
          <h4 class="media-heading"><%= link_to product.name, potepan_product_path(product.id) %></h4>
          <p><%= product.description %></p>
          <h3><%= product.master.price %><%= product.cost_currency %></h3>
          <div class="btn-group" role="group">
            <button type="button" class="btn btn-default" data-toggle="modal" data-target=".login-modal"><i class="fa fa-heart" aria-hidden="true"></i></button>
            <button type="button" class="btn btn-default" onclick="location.href='cart-page.html';"><i class="fa fa-shopping-cart" aria-hidden="true"></i></button>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>
<%= content_tag :div, paginate(@products_of_taxon), class: 'text-center' %>

app/views/potepan/categories/show.html.erb
<%= provide(:title, @taxon.name)%>

<!-- LIGHT SECTION -->
<section class="lightSection clearfix pageHeader">
  <div class="container">
    <div class="row">
      <div class="col-xs-6">
        <div class="page-title">
          <h2><%= yield(:title) %></h2>
        </div>
      </div>
      <div class="col-xs-6">
        <ol class="breadcrumb pull-right">
          <li>
            <%= link_to 'Home', potepan_root_path %>
          </li>
          <li>
            <%= link_to 'Shop', '#' %>
          </li>
          <li class="active">
              <%= @taxon.name %>
          </li>
        </ol>
      </div>
    </div>
  </div>
</section>

<section class="mainContent clearfix productsContent">
  <div class="container">
    <%= render 'potepan/shared/sidebar' %>
    <div class="col-md-9 col-sm-8 col-xs-12">
      <%= render 'potepan/shared/filter_products' %>
      <div class="tab-content">
        <div class="tab-pane on"><%= render 'potepan/categories/products_grid' %></div>
        <div class="tab-pane"><%= render 'potepan/categories/products_list' %></div>
      </div>
    </div>
  </div>
 </section>

 <%= render 'potepan/shared/modal_content' %>

app/views/potepan/products/_light_section.html.erb
<section class="lightSection clearfix pageHeader">
  <div class="container">
    <div class="row">
      <div class="col-xs-6">
        <div class="page-title">
          <h2><%= yield(:title) %></h2>
        </div>
      </div>
      <div class="col-xs-6">
        <ol class="breadcrumb pull-right">
          <li>
            <%= link_to 'Home', potepan_root_path %>
          </li>
          <li>
            <%= link_to 'Shop', '#' %>
          </li>
          <li class="active">
            <%= yield(:title) %>
          </li>
        </ol>
      </div>
    </div>
  </div>
</section>

app/views/potepan/products/_products_grid_by_color_filter.html.erb
<div class="row">
  <%= content_tag :div, paginate(@variants), class: 'text-center' %>
  <% @variants.each do |variant| %>
      <div class="col-sm-4 col-xs-12">
        <div class="productBox">
          <div class="productImage clearfix">
            <%= image_tag(variant.display_image.attachment(:small)) %>
            <div class="productMasking">
              <ul class="list-inline btn-group" role="group">
                <li><a data-toggle="modal" href=".login-modal" class="btn btn-default"><i class="fa fa-heart"></i></a></li>
                <li><a href="cart_page.html" class="btn btn-default"><i class="fa fa-shopping-cart"></i></a></li>
                <li><a class="btn btn-default" data-toggle="modal" href=".quick-view" ><i class="fa fa-eye"></i></a></li>
              </ul>
            </div>
          </div>
          <div class="productCaption clearfix">
            <h5><%= link_to variant.name, potepan_product_path(variant.product.id) %></h5>
            <h5><%= @tshirt_size = variant.option_value('tshirt-size') %><%= "size" if @tshirt_size %></h5>
            <h3><%= variant.price %><%= variant.cost_currency %></h3>
          </div>
        </div>
      </div>
  <% end %>
</div>
<%= content_tag :div, paginate(@variants), class: 'text-center' %>

app/views/potepan/products/_products_list_by_color_filter.html.erb
<div class="row productListSingle">
  <%= content_tag :div, paginate(@variants), class: 'text-center' %>
  <% @variants.each do |variant| %>
    <div class="col-xs-12">
      <div class="media">
        <div class="media-left">
          <%= image_tag(variant.display_image.attachment(:product)) %>
          <span class="maskingImage"><a data-toggle="modal" href=".quick-view" class="btn viewBtn">Quick View</a></span>
        </div>
        <div class="media-body">
          <h4 class="media-heading"><%= link_to variant.name, potepan_product_path(variant.product.id) %></h4>
          <p><%= variant.description %></p>
          <p><%= @tshirt_size = variant.option_value('tshirt-size') %><%= "size" if @tshirt_size %></p>
          <h3><%= variant.price %><%= variant.cost_currency %></h3>
          <div class="btn-group" role="group">
            <button type="button" class="btn btn-default" data-toggle="modal" data-target=".login-modal"><i class="fa fa-heart" aria-hidden="true"></i></button>
            <button type="button" class="btn btn-default" onclick="location.href='cart-page.html';"><i class="fa fa-shopping-cart" aria-hidden="true"></i></button>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>
<%= content_tag :div, paginate(@variants), class: 'text-center' %>

app/views/potepan/products/_related_product.html.erb
<div class="col-md-3 col-sm-6 col-xs-12">
  <div class="productBox">
    <div class="productImage clearfix">
      <%= image_tag((related_product.images[0]).attachment(:small)) %>
      <div class="productMasking">
        <ul class="list-inline btn-group" role="group">
          <li><a data-toggle="modal" href=".login-modal" class="btn btn-default"><i class="fa fa-heart"></i></a></li>
          <li><a href="cart_page.html" class="btn btn-default"><i class="fa fa-shopping-cart"></i></a></li>
          <li><a class="btn btn-default" data-toggle="modal" href=".quick-view" ><i class="fa fa-eye"></i></a></li>
        </ul>
      </div>
    </div>
    <div class="productCaption clearfix">
     <h5><%= link_to related_product.name, potepan_product_path(related_product.id) %></h5>
     <h3><%= related_product.price %><%= related_product.cost_currency %></h3>
    </div>
  </div>
</div>

app/views/potepan/products/index.html.erb
<%= provide(:title, active_title(color: @color)) %>

<!-- LIGHT SECTION -->
<%= render 'light_section' %>

<section class="mainContent clearfix productsContent">
  <div class="container">
    <%= render 'potepan/shared/sidebar' %>
    <div class="col-md-9 col-sm-8 col-xs-12">
      <%= render 'potepan/shared/filter_products' %>
        <div class="tab-content">
          <div class="tab-pane on"><%= render 'potepan/products/products_grid_by_color_filter' %></div>
          <div class="tab-pane"><%= render 'potepan/products/products_list_by_color_filter' %></div>
        </div>
    </div>
  </div>
</section>

<%= render 'potepan/shared/modal_content' %>

app/views/potepan/products/show.html.erb
<%= provide( :title, @product.name )%>

<!-- LIGHT SECTION -->
<%= render 'light_section' %>

<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix">
  <div class="container">
    <div class="row singleProduct">
      <div class="col-xs-12">
        <div class="media">
          <div class="media-left productSlider">
            <div id="carousel" class="carousel slide" data-ride="carousel">
              <div class="carousel-inner">
                  <% (@product.variant_images).each_with_index do |image,index| %>
                    <div class="item <%= index.zero? ? 'active' : '' %>" data-thumb="<%= "#{index}" %>"><%= image_tag(image.attachment(:product)) %></div>
                  <% end %>
              </div>
            </div>
            <div class="clearfix">
              <div id="thumbcarousel" class="carousel slide" data-interval="false">
                <div class="carousel-inner">
                  <% (@product.variant_images).each_with_index do |image,index| %>
                    <div data-target="#carousel" data-slide-to="<%= index %>" class="thumb">
                      <%= image_tag(image.attachment(:small)) %>
                    </div>
                  <% end %>
                </div>
                <a class="left carousel-control" href="#thumbcarousel" role="button" data-slide="prev">
                  <span class="glyphicon glyphicon-chevron-left"></span>
                </a>
                <a class="right carousel-control" href="#thumbcarousel" role="button" data-slide="next">
                  <span class="glyphicon glyphicon-chevron-right"></span>
                </a>
              </div>
            </div>
          </div>
          <div class="media-body">
            <ul class="list-inline">
              <li><a href="#"><i class="fa fa-reply" aria-hidden="true"></i>一覧ページへ戻る</a></li>
            </ul>
            <h2><%= @product.name %></h2>
            <h3><%= @product.price %><%= @product.cost_currency %></h3>
            <p><%= @product.description %></p>
            <% (@product.option_types).each_with_index do |types, index| %>
              <% presentations = types.option_values.pluck(:presentation, :id) %>
                <span class="quick-drop">
                  <%= select_tag types.name, options_for_select( presentations, :selected =>presentations[0]), { class: 'select-drop'} %>
                </span>
              <% end %>
            <span class="quick-drop resizeWidth">
              <select name="guiest_id4" id="guiest_id4" class="select-drop">
              <!--   <option value="0">Qty</option> -->
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
              </select>
            </span>
            <div class="btn-area">
              <a href="cart_page.html" class="btn btn-primary btn-block">カートへ入れる<i class="fa fa-angle-right" aria-hidden="true"></i></a>
            </div>
            <div class="tabArea">
              <ul class="nav nav-tabs">
                <li class="active"><a data-toggle="tab" href="#details">details</a></li>
                <li><a data-toggle="tab" href="#about-art">about art</a></li>
                <li><a data-toggle="tab" href="#sizing">sizing</a></li>
                <li><a data-toggle="tab" href="#shipping">shipping</a></li>
              </ul>
              <div class="tab-content">
                <div id="details" class="tab-pane fade in active">
                  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
                  <ul class="list-unstyled">
                    <% (@product.properties).each do |property| %>
                    <li><%= property.presentation %></li>
                    <% end %>
                  </ul>
                </div>
                <div id="about-art" class="tab-pane fade">
                  <p>Nulla facilisi. Mauris efficitur, massa et iaculis accumsan, mauris velit ultrices purus, quis condimentum nibh dolor ut tortor. Donec egestas tortor quis mattis gravida. Ut efficitur elit vitae dignissim volutpat. </p>
                </div>
                <div id="sizing" class="tab-pane fade">
                  <p>Praesent dui felis, gravida a auctor at, facilisis commodo ipsum. Cras eu faucibus justo. Nullam varius cursus nisi, sed elementum sem sagittis at. Nulla tellus massa, vestibulum a commodo facilisis, pulvinar convallis nunc.</p>
                </div>
                <div id="shipping" class="tab-pane fade">
                  <p>Mauris lobortis augue ex, ut faucibus nisi mollis ac. Sed volutpat scelerisque ex ut ullamcorper. Cras at velit quis sapien dapibus laoreet a id odio. Sed sit amet accumsan ante, eu congue metus. Aenean eros tortor, cursus quis feugiat sed, vestibulum vel purus.</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="row productsContent">
      <div class="col-xs-12">
        <div class="page-header">
          <h4>関連商品</h4>
        </div>
      </div>
      <%= render partial: 'related_product', collection: @related_products %>
    </div>
  </div>
</section>

app/views/potepan/shared/_filter_products.html.erb
<div class="row filterArea">
  <div class="col-xs-6">
    <select name="guiest_id1" id="guiest_id1" class="select-drop">
      <option value="0">Default sorting</option>
      <option value="1">Sort by popularity</option>
      <option value="2">Sort by rating</option>
      <option value="3">Sort by newness</option>
      <option value="3">Sort by price</option>
    </select>
  </div>
  <div class="col-xs-6">
    <div class="nav nav-tab">
      <div role="group" class="btn-group pull-right">
        <button href="#tab1" id="btn1" data-toggle="tab" class="btn btn-default on"><i class="fa fa-th" aria-hidden="true"></i><span>Grid</span></button>
        <button href="#tab2" id="btn2" data-toggle="tab" class="btn btn-default"><i class="fa fa-th-list" aria-hidden="true"></i><span>List</span></button>
      </div>
    </div>
  </div>
</div>

app/views/potepan/shared/_side_categories.html.erb
<% @taxonomies.each do |taxon_root| %>
  <div class="panel panel-default">
    <div class="panel-heading"><%= taxon_root.name %></div>
    <div class="panel-body">
      <div class="collapse navbar-collapse navbar-ex1-collapse navbar-side-collapse">
        <ul class="nav navbar-nav side-nav">
          <% (taxon_root.taxons).each do |taxon_children| %>
            <% next if taxon_children.depth == 0 %>
            <% if taxon_children.depth == 1 %>
              <li class="side-nav-list">
                <% if taxon_children.children.any? %>
                  <a><i class="fa fa-plus"></i><%= taxon_children.name %></a>
                <% else %>
                  <%= link_to taxon_children.name, potepan_category_path(taxon_children.id) %>
                <% end %>
                <% if taxon_children.children.any? %>
                  <ul id="<%= taxon_children.name.downcase %>" class="side-nav-close collapse collapseItem">
                    <% (taxon_children.children).each do |child| %>
                      <li>
                        <%= link_to potepan_category_path(child.id) do %>
                          <i class="fa fa-caret-right" aria-hidden="true"></i><%= child.name %> <span>(<%= child.products.size %>)</span></a>
                        <% end %>
                      </li>
                    <% end %>
                  </ul>
                <% end %>
              </li>
            <% end %>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
<% end %>

app/views/potepan/shared/_side_filter.html.erb
<div class="panel panel-default priceRange">
  <div class="panel-heading">値段から探す</div>
  <div class="panel-body clearfix">
    <div class="price-slider-inner">
      <span class="amount-wrapper">
        <input type="text" id="price-amount-1" readonly>
        <strong>-</strong>
        <input type="text" id="price-amount-2" readonly>
      </span>
      <div id="price-range"></div>
    </div>
    <input class="btn btn-default" type="submit" value="絞り込む">
  </div>
</div>
<div class="panel panel-default filterNormal">
  <div class="panel-heading">色から探す</div>
  <div class="panel-body">
    <ul class="list-unstyled">
      <% @hash_classification_by_filter[:labels].each do |label| %>
        <li>
          <%= link_to potepan_products_path(color: label.name) do %>
            <%= label.name %><span>(<%= @hash_classification_by_filter[:counts][label.name] %>)</span>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</div>
<div class="panel panel-default filterNormal">
  <div class="panel-heading">サイズから探す</div>
  <div class="panel-body">
    <ul class="list-unstyled clearfix">
      <li><a href="#">S<span>(15)</span></a></li>
      <li><a href="#">M<span>(10)</span></a></li>
      <li><a href="#">L<span>(7)</span></a></li>
      <li><a href="#">XL<span>(12)</span></a></li>
    </ul>
  </div>
</div>